### ISSUE TITLE
Fix for stack trace in console 

### ISSUE THREAD

**Issue by akondasif** [mvitz/javaspektrum-quarkus#2]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/

Fix: https://github.com/mvitz/javaspektrum-quarkus/pull/1

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by mvitz** [comment]
Hi,

the insecure coding pattern you found is in a generated script that is used to download maven (via maven wrapper) if the correct maven version is not present. The stack trace is only ever printed to the person building this project and has nothing to do with the application itself.

Therefore I don't consider this a security issue and it won't be fixed here.
